apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-jenkins
  namespace: test-project
  labels:
    app: test-project
spec:
  selector:
    matchLabels:
      app: test-project
  replicas:
  strategy: 
    type:
    rollingUpdate:
  template:
    metadata:
      labels:
        app: test-project
    spec:
      containers:
      - name: test-jenkins
        image: "sujitsingh1/jenkins-test-test:main"
        resources:
          limits:
            cpu: 128m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi  
        envFrom:
        - secretRef:
            name: test-jenkins
        imagePullPolicy:
        ports:
        - containerPort:
      nodeSelector:
        allowed:
      tolerations:
      - effect:
        key:
        operator:
        value:         
      imagePullSecrets:
        - name:
---

apiVersion:
kind: Service
metadata:
  name: test-jenkins
  namespace: test-project
spec:
  selector:
    app: test-project
  type:
  ports:
  - protocol:
    port:
    targetPort:
---
apiVersion:
kind:
metadata:
  name: test-jenkins
  namespace: test-project
spec:
  scaleTargetRef:
    apiVersion:
    kind: Deployment
    name: test-jenkins
  minReplicas:
  maxReplicas:
  metrics:
  - type:
    resource:
      name:
      target:
        type:
        averageValue:
  - type:
    resource:
      name:
      target:
        type:
        averageValue:    
  behavior:
    scaleDown:
      stabilizationWindowSeconds:
      policies:
      - type:
        value:
        periodSeconds:
      selectPolicy: